#!/usr/bin/env bash

view="[$0]:"
osre="/usr/lib/os-release"
lsbre="/etc/lsb-release"

# os-releaseとlsb-releaseのバックアップ先です。自由に変更できます。
# MEMO: $HOMEが/home/"user" から /root に変わる（sudoで実行してるから？）
osre_bak="$HOME/os-release.bak"
lsbre_bak="$HOME/lsb-release.bak"

oldname=$(lsb_release -d | awk -F "\t" '{print $2}' | awk 'BEGIN{ORS = ""}{print $0}')

# error_window関数
error_window () {
    zenity \
    --error \
    --width 350 \
    --title $0 \
    --text "${1}"
    exit 0

}

# info_window関数
info_window () {
    zenity \
    --info \
    --width 350 \
    --title $0 \
    --text "${1}"
    exit 0

}

# エラー出力
errprint () {
    printf "${view} \033[31m${1}\033[m\n"
    error_window "${1}"
}

# OK出力
okprint () {
    printf "${view} \033[32m${1}\033[m\n"
}

# 処理を呼び出す
call () {
    bash $0
}

# パスワード入力のGUI化（pkexec）
if [ ! $UID = 0 ]; then
    pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY $0
    exit 0

fi

# ファイル有無の確認
if [ -e $osre ]; then
    okprint "${osre} found."

    if [ -e $lsbre ]; then
    okprint "${lsbre} found."

    else
        errprint "${lsbre} not found."

    fi

else
    errprint "${osre} not found."

fi

# メインメニュー
select=$(
    zenity \
    --title $0 \
    --info \
    --text "Select the functions..." \
    --ok-label="Close" \
    --extra-button="Change name" \
    --extra-button="Restore"

)

mainmenu=$?

case $mainmenu in
    0)
        exit 0
        
    ;;
    *)
        :

    ;;
esac

case $select in
    "Change name")
        # Change name
        sudo cp $osre $osre_bak || errprint "Error. Failed to copy the file\"${osre}\"."
        okprint "${osre} has been backed up."

        sudo cp $lsbre $lsbre_bak || errprint "Error. Failed to copy the file\"${lsbre}\"."
        okprint "${lsbre} has been backed up."

        okprint "The back up was complate."

        newname=$(
            zenity \
            --entry \
            --title $0 \
            --text "Please new DistroName..."
            
            )

        entry=$?

        case $entry in
            0)
                zenity \
                --question \
                --width 350 \
                --title $0 \
                --text "Change \"${oldname}\" to \"${newname}\" ."

                lastcheck=$?

                case $lastcheck in
                    0)
                        # 本処理
                        sudo sed -i "5 s/${oldname}/${newname}/" $osre || errprint "Error. Failed to edit the file\"${osre}\"."
                        okprint "The changes was complete to \"${osre}\""

                        sudo sed -i "4 s/${oldname}/${newname}/" $lsbre || errprint "Error. Failed to edit the file\"${lsbre}\"."
                        okprint "The changes was complete to \"${lsbre}\""

                        info_window "Changes completed successfully."

                    ;;
                    1)
                        :
                    
                    ;;
                esac
            ;;
            1)
                :
            
            ;;
        esac

    ;;
    "Restore")
        # Restore
        if [ -e $osre_bak ]; then
            okprint "${osre_bak} found."

            if [ -e $lsbre_bak ]; then
            okprint "${lsbre_bak} found."

            else
                errprint "${lsbre_bak} not found."

            fi
        else
            errprint "${osre_bak} not found."

        fi

        # バックアップされたos-releaseのos名を取得
        bakname=$(cat ${osre_bak} | head -n5 | tail -n1 | cut -c 13- | sed 's/^.*"\(.*\)".*$/\1/')

        zenity \
        --question \
        --width 350 \
        --title $0 \
        --text "Do you want to restore the files?\nChange \"${oldname}\" to \"${bakname}\" ."

        restore=$?

        case $restore in
            0)
                # 本処理
                sudo cp $osre_bak $osre || errprint "Error. Failed to copy the file\"${osre_bak}\"."
                okprint "Restoration of ${osre} is complete."

                sudo cp $lsbre_bak $lsbre || errprint "Error. Failed to copy the file\"${lsbre_bak}\"."
                okprint "Restoration of ${lsbre} is complete."

                okprint "Restore completed successfully."
                info_window "Restore completed successfully."
            ;;
            1)
                :
            ;;
        esac

    ;;
    *)
        errprint "Error. Exception occured."

    ;;
esac


call